url: https://clangwarnings.com
title: Clang Warnings
description: A list of Clang warnings and their descriptions.

include:
  - .well-known

exclude:
  - netlify.toml
  - LICENSE
  - README.md
  - Procfile

plugins:
  - jekyll-assets
  - jekyll-tidy
