[[redirects]]
  from = "https://clangwarnings.netlify.com/*"
  to = "https://clang.llvm.org/docs/DiagnosticsReference.html"

[[redirects]]
  from = "http://clangwarnings.netlify.com/*"
  to = "https://clang.llvm.org/docs/DiagnosticsReference.html"

[[redirects]]
  from = "https://clangwarnings.com/*"
  to = "https://clang.llvm.org/docs/DiagnosticsReference.html"

[[redirects]]
  from = "http://clangwarnings.com/*"
  to = "https://clang.llvm.org/docs/DiagnosticsReference.html"

